// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_reach_150_scores = "CgkIq4mShcYREAIQAw"; // <GPGSID>
        public const string achievement_reach_50_scores = "CgkIq4mShcYREAIQAQ"; // <GPGSID>
        public const string achievement_reach_500_scores = "CgkIq4mShcYREAIQBQ"; // <GPGSID>
        public const string leaderboard_bouncing_ball_leaderboard = "CgkIq4mShcYREAIQBg"; // <GPGSID>
        public const string achievement_reach_200_scores = "CgkIq4mShcYREAIQBA"; // <GPGSID>
        public const string achievement_reach_100_scores = "CgkIq4mShcYREAIQAg"; // <GPGSID>

}

